_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 4
checkpoint_name:
    value: test.pth
learning_rate:
    value: 0.0001
num_epochs:
    value: 10
